import './global.css';
import { ReactNode } from "react";
import { randomBgColor } from "./components/user-avatar/user-avatar";

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {

  randomBgColor();
  return (
    <html className="h-full bg-gray-900" lang="en">
      <body className="h-full flex justify-center">
        <div id="content-container" className="w-[64rem]">
          <div className="px-20 pt-4 w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
