import './global.css';
import { ReactNode } from 'react';
import { LayoutWrapper } from './layout-wrapper';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="h-full bg-white dark:bg-gray-900 flex justify-center">
        <div id="content-container" className="w-[64rem]">
          <div className="px-20 pt-4 w-full">
            <LayoutWrapper>{children}</LayoutWrapper>
          </div>
        </div>
      </body>
    </html>
  );
}
